### ISSUE TITLE
conda uncontrollably spawning python processes when creating/removing envs

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/menuinst#42] opened 2017-05-05 16:50 UTC
_From @cwreid18 on March 2, 2017 16:48_

On Windows 7, with Anaconda installed for all users in C:\Anaconda3. No problem creating and removing envs with admin rights. However, when running as user without admin rights, I get the following problem when creating environments: packages are downloaded ok, but then it hangs (usually at the linking or unlinking packages step) and I can see pythonw.exe processes being launched in task manager at a rate of several per second. Only way to stop this is to shut down the machine. The problem is intermittent and seems to occur more frequently when creating envs with all the anaconda packages (e.g. conda create -n test anaconda=4.1.1) rather than environments that only contain a few packages. Happens occasionally when trying to remove envs. I have tried reinstalling with multiple versions of anaconda (inc. the latest, 4.3.0) but the problem keeps occurring.

_Copied from original issue: conda/conda#4782_

**Comment by kalefranz** [comment] 2017-05-05 16:50
What version of conda?  Can you provide `conda info`?  If you're not on 4.3.13, go ahead an upgrade with `conda update conda` (as admin) and see if the problem is still there.

**Comment by kalefranz** [comment] 2017-05-05 16:50
_From @cwreid18 on March 2, 2017 17:59_

4.3.8 was the most recent version I used previously. The admin isn't around but I was able to update conda to 4.3.13 on my user. I then tried `conda create -n test anaconda=4.1.1` and got the error described above.

**Comment by kalefranz** [comment] 2017-05-05 16:50
_From @cwreid18 on March 2, 2017 18:7_

![conda_info](https://cloud.githubusercontent.com/assets/26145704/23520477/160068ee-ff73-11e6-86c4-693815543296.png)

**Comment by kalefranz** [comment] 2017-05-05 16:50
_From @wulmer on March 14, 2017 13:0_

I am having the same issue with conda 4.3.13. This problem currently blocks our Jenkins builds on Windows... :-(
It seems that if there is a problem while creating an environment, conda retries again and again. (Each of the failed processes spawns a new subprocess which also fails and which also starts a new subprocess and so on...)

I was able to get the command line of the spawned Python processes. It always reads the same:

    "C:\Program Files\Anaconda3\pythonw.exe" "-c" "import menuinst; menuinst.install('c:\\Jenkins\\WORKSP~1\\XQ_MUL~1\\FED2B2~1\\virtual-env2\\Menu\\spyder_shortcut.json', False, 'c:\\Jenkins\\WORKSP~1\\XQ_MUL~1\\FED2B2~1\\virtual-env2')"

As I don't run with admin rights (and AFAIK creating start menu shortcuts with conda shows a UAC prompt) I assume that my background Jenkins process tries to get a UAC approval but can't as it is running in the background. So somehow conda tries it again over and over...

I will try to change my env setup commands to skip menu shortcut creation... hope this avoids the issue...

My conda install is:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.1.5
         python version : 3.6.0.final.0
       requests version : 2.13.0
       root environment : C:\Program Files\Anaconda3  (read only)
    default environment : C:\Program Files\Anaconda3

**Comment by kalefranz** [comment] 2017-05-05 16:50
To my knowledge there is no "retry" in conda (there is in conda-build).  And it's possible that menuinst is the problem.  An easy test would just be `conda uninstall menuinst`, which shouldn't cripple conda at all.

**Comment by kalefranz** [comment] 2017-05-05 16:50
_From @asishm on March 31, 2017 13:12_

@wulmer Could you tell how you were able to get the command line of the spawned Python processes?

**Comment by kalefranz** [comment] 2017-05-05 16:50
_From @wulmer on March 31, 2017 21:7_

@asishm I use ProcessHacker (http://processhacker.sf.net) which not only shows process dependencies but also much more interesting and helpful information (for debugging), e.g. it can show command lines, working directories or environment variables of processes. Has saved me lots of time...

**Comment by kalefranz** [comment] 2017-05-05 16:50
_From @asishm on April 1, 2017 18:1_

Thanks,

I verified and I have the same issue. The `menuinst` keeps spawning multiple child processes. Since I don't have admin access, I can't run `conda uninstall menuinst` until I can get the sysadmin process it, which takes a very long time due to company procedures.

I'm trying to create conda envs with the default anaconda packages  with `conda create -n full_env python=3.5 anaconda` and since `menuinst` is a default package, it shows up. Is there any way to exclude that?

**Comment by bk-m** [comment] 2017-09-06 12:00
I just ran into the same (or a very similar) problem when running `conda install pandas=0.19`. A ridiculous amount of python processes were spawned to a point where my computer froze.

One thing I noticed is that this only happened when I ran the command with user-level access. Running the command while logged in to an admin account worked perfectly fine.

**Comment by jgmorrison** [comment] 2017-10-11 15:41
The general issue is when this is an All User install and users do not have write permissions. Especially when a user tries to create an environment with the anaconda package in it.

    conda create -n myenv python=2.7 anaconda

 The Pythonw.exe process wants to launch a window(GUI for pythonw.exe from menuinst) to request the admin password every time the installer hits a package that has a Start Menu item. Elevated permissions are required because it is trying to install this Start Menu item for every user. Anaconda is not a very great multi user installation in this way and this error has been happening for well over a year or more.

If they want anaconda in their environment they should just install the Anaconda software for each user in their home directory. The other solutions to avoid menuinst are just excessive compared to installing Anaconda on a per user basis.

**Comment by JoeHartshorn** [comment] 2017-12-20 16:38
If I wanted to solve this bug by changing the process to only install start menu items for one user, or not install start menu items at all, where would I start? Which package should I look to contribute to?

**Comment by Ritcho** [comment] 2018-03-08 23:16
Desktop admin here, this issue appears to be a rights issue in windows, a standard user doesn't have the privileges to create a symbolic link, our granular admin rights management program identifies this as object "SeCreateSymbolicLinkPriviledge", see below for reference:
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links

When an env is created that includes Jupyter using Anaconda-navigator all actions succeed except the creation of the env specific shortcut in the start menu which triggers the UAC

**Comment by Ritcho** [comment] 2018-03-08 23:34
This could be one of the edge cases mentioned on line 210 of
https://github.com/ContinuumIO/menuinst/blob/master/menuinst/windows/win32.py

**Comment by Ritcho** [comment] 2018-03-09 00:57
This works in PowerShell, don't know whether it helps you

$s = (New-Object -COM WScript.Shell).CreateShortcut($env:ProgramData + '\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)\test.lnk')
$s.TargetPath = 'c:\temp\Test.txt'
$s.Save()

**Comment by plu2k** [comment] 2018-04-09 10:56
Has there been any progress on this issue? I have the same problem on a company machine running Windows 7. Removing menuinst is not a great option because it seems to be a dependency of conda-build (and anaconda of course, for that matter). Killing the pythonw process works, but wanting to promote the use of anaconda, this is not something I am eager to advise colleagues to do.

**Comment by mingwandroid** [comment] 2018-04-09 11:08
@Richto, the symlinks (proper, Unix-a-like ones) related to `SeCreateSymbolicLinkPriviledge` have nothing to do with `Start Menu` shortcuts.

**Comment by jengelman** [comment] 2018-04-30 19:59
This issue also occurs when you try to update (or uninstall) anything that uses menuinst, which includes ipython and notebook.  I was able to get around it/avoid crashing my computer by manually killing every pythonw instance with pskill, but a less hacky solution would be greatly appreciated.

**Comment by csoja** [comment] 2018-05-17 18:18
@msarahan  Can this be closed? (Is this fixed in menuinst 1.4.12?)

**Comment by msarahan** [comment] 2018-05-17 18:31
I believe so.  I did attempt to fix this in https://github.com/ContinuumIO/menuinst/pull/67

I understand how the problem arose, but I ultimately couldn't reproduce it.  I asked affected people to test, but none responded.  So yes, let's close it and keep our fingers crossed.

**Closed by msarahan** 2018-05-17 18:31 UTC

**Comment by j-hartshorn** [comment] 2018-05-17 18:35
Apologies for the late reply, the issue is resolved for me. Now when menuinst tries and fails to create a menu item as part of a package install, it shows a log entry and continues anyway.
