### ISSUE TITLE
Incompatible cwp.py and menuinst package

### ISSUE THREAD

**Issue by wulmer** [ContinuumIO/menuinst#46] opened 2017-05-30 11:20 UTC
Start menu shortcuts pull in multiple components to open a Python application, for example:

    C:\path\to\venv\pythonw.exe \                # the Python executable from the VIRTUAL env
    "C:\Program Files\Anaconda3\cwp.py" \        # the cwp script from the ROOT env
    C:\path\to\venv \                            # the VIRTUAL env directory
    "C:/path/to/venv/pythonw.exe" \              # the Python executable from the VIRTUAL env
    "C:/path/to/venv/Scripts/spyder-script.py"   # the application script from the VIRTUAL env

As you can easily see, the call of the `cwp.py` script is done through the interpreter from the virtual environment. What happened on my computers is that the `menuinst` package (which currently has to be installed in the root env) was not compatible to the `cwp.py` script which made the whole shortcut fail silently.

Shouldn't the first part call the Python interpreter from the ~~virtual~~ *root* environment instead of the interpreter from the ~~root~~ *virtual* environment? Then, the `menuinst` package from the root environment would be used.

**Comment by msarahan** [comment] 2017-05-30 13:55
@wulmer can you help me understand the circumstances under which these incorrect shortcuts are created?

It looks to me like this is the prefix that is used for the first entry: https://github.com/ContinuumIO/menuinst/blob/master/menuinst/win32.py#L137

I'm confused here, though - how is sys.prefix *ever* anything other than the root python version?  Are you somehow calling menuinst directly rather than conda calling it?  If conda is calling it, I think it should always be the root python that conda is using?

CC @mingwandroid - any ideas here, Ray?

**Comment by mingwandroid** [comment] 2017-05-30 14:08
To the best of my knowledge, menuinst is only ever called from the root env so no, no idea at all here!

**Comment by mbargull** [comment] 2017-05-30 16:20
The problem is that in https://github.com/ContinuumIO/menuinst/blob/master/menuinst/win32.py#L254
```python
        if "pywscript" in self.shortcut:
            cmd = join(self.menu.prefix, u"pythonw.exe").replace("\\", "/")
            args = self.shortcut["pywscript"].split()
            args = get_python_args_for_subprocess(self.menu.prefix, args, cmd)
```
sets `cmd` which is later assumed to be referring to the root prefix. It should actually be
```python
        if "pywscript" in self.shortcut:
            subprocess_cmd = join(self.menu.prefix, u"pythonw.exe").replace("\\", "/")
            args = self.shortcut["pywscript"].split()
            args = get_python_args_for_subprocess(self.menu.prefix, args, subprocess_cmd)
            cmd = join(unicode_prefix, u"pythonw.exe").replace("\\", "/")
```
I.e., the `cmd` variable shouldn't refer to (possibly, e.g., when in non-root env) distinct values/commands. This also affects the other branches of the if-elif-else-clause: all those `cmd` should be renamed to `subprocess_cmd` when they do not refer to the root one. Sorry I haven't time for a PR, but it should be straight forward to make the explained changes :smile: .

**Comment by msarahan** [comment] 2017-05-30 16:27
no worries @mbargull - thanks for reasoning this out.

**Comment by samedi2k** [comment] 2017-08-02 10:09
I have the same issue. When I install spyder in an environment (e.g. 'tensorflow') it will create the following shortcut target in Win 10 start menu:

`C:\Users\abc\Anaconda3\envs\tensorflow\python.exe C:\Users\abc\Anaconda3\cwp.py C:\Users\abc\Anaconda3\envs\tensorflow "C:/Users/abc/Anaconda3/envs/tensorflow/python.exe" "C:/Users/abc/Anaconda3/envs/tensorflow/Scripts/ipython-script.py"`

Problem ist that the cwp.py script (which is abviously in root) is called by the interpreter from tensorflow environment. This environment uses an older version of python which is obviously not compatible with cwp.py

Solution:

Just make sure that cwp.py is called by root python. So correct version looks like this:

`C:\Users\abc\Anaconda3\python.exe C:\Users\abc\Anaconda3\cwp.py C:\Users\abc\Anaconda3\envs\tensorflow "C:/Users/abc/Anaconda3/envs/tensorflow/python.exe" "C:/Users/abc/Anaconda3/envs/tensorflow/Scripts/ipython-script.py"`

Hope this could be fixed in anaconda directly.

**Comment by dashesy** [comment] 2017-08-09 23:17
@samedi2k In the VM I was seeing the issue the root Anaconda Python version is 2.7

    $ C:\Anaconda\Python.exe --version
    Python 2.7.11 :: Anaconda custom (64-bit)

But the environment that is setup `py35` is Python3.5
When I use the root Python instead of the one from the environment it works.
So it is not being old vs new exactly, just incompatibility.

**Comment by samedi2k** [comment] 2017-08-10 07:18
@dashesy Yes exactly, that's the point. In my case root is 3.6 and env is 3.5 which also does not work. Solution is super easy: execute cwp.py by the root interpreter and not the env interpreter as I pointed out above. If shortcut generator could be fixed accordingly, that would be great.

**Comment by msarahan** [comment] 2017-08-10 18:31
Sorry, the PR fixing this never got merged.  We'll get it sorted out soon.

**Comment by mingwandroid** [comment] 2017-10-26 10:04
This is now fixed (along with the things it broke).

**Closed by mingwandroid** 2017-10-26 10:04 UTC

**Comment by mbargull** [comment] 2017-10-26 12:17
Hi @mingwandroid, sorry, I hadn't followed the further development on this issue. Seems @msarahan's PR was merged before mine for his branch: https://github.com/msarahan/menuinst/pull/1 (which I apparently didn't advertise enough, sorry..).
Reading your commit message for fcf395dbc7ccfd5130b2c38a243056820034081f
>I have made it so that 'script' still does this but 'system' does not

I suppose you did the same, which I suppose should be the correct behavior.

**Comment by mingwandroid** [comment] 2017-10-26 12:19
No problem. It's our lack of good tests that's the real issue here. Thanks for the contributions.

**Comment by mbargull** [comment] 2017-10-26 13:30
Oh boy, yeah, it's complicated to review the changes without test cases... Maybe you could start a PR with some test cases I (and others) could contribute some more to?
It is very complicated (and, I believe, for the general case [nearly] impossible) to get quoting & co. right for Windows, especially when CMD is involved, too.
For the long-term I hope we could work something out which can circumvent some of those issues. Possibly this could be incorporated into the work proposed in https://github.com/ContinuumIO/menuinst/issues/48.

**Comment by mingwandroid** [comment] 2017-10-26 13:36
This is essential reading (if somewhat tedious):

https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

PRs to add tests welcome, I do not expect I will have any time to look at menuinst until the next release of AD, and only then if there is another bad bug in it.

**Comment by dashesy** [comment] 2017-10-26 18:30
I wonder why there are all those `.replace('/', '\\')` in the code. In Windows (since 7), forward slash is a perfectly valid directory separator.

**Comment by mingwandroid** [comment] 2017-10-26 18:32
Because standardizing on one or the other is better than having them mixed and, despite your claim, there are loads of bits of Windows that do not handle `/` *at all*.

**Comment by dashesy** [comment] 2017-10-26 19:16
Can you please elaborate where exactly `/` will not work in Windows since 7? It even works in `CMD.exe` just try `cd c:/Windows`
Even then `os.path.normpath` should be used instead of `replace`.

**Comment by mingwandroid** [comment] 2017-10-26 19:38
> Can you please elaborate where exactly `/` will not work in Windows since 7? It even works in CMD.exe just try `cd c:/Windows`

Yes I can, easily:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\builder>copy C:\Windows\System32/cmd.exe %UserProfile%
The syntax of the command is incorrect.

C:\Users\builder>
```

If I change those shortcuts so that they have any `/` in them then that is something that comes through to `argv[0]` of the program that they point to. Some programs will parse `argv[0]` and not all of them will be written to handle `/` correctly (or at all). The thing you must remember is that the `Anaconda Distribution` supports running many arbitrary programs and therefore we must *always* strive to pick the *most compatible* option.

Besides that, having mixed `\` and `/` is ugly.

> Even then os.path.normpath should be used instead of replace.

Your opinion is noted.
